name: Run tests
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: python -m pip install -r requirements.txt
 
    - name: Install packages
      run: |
        pip install pytest
        python setup.py build_lib
        pip install -e .
        pytest
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: python -m pip install -r requirements.txt
 
    - name: Install packages
      run: |
        pip install pytest
        python setup.py build_lib
        pip install -e .
        pytest
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: python -m pip install -r requirements.txt
 
    - name: Install packages
      run: |
        pip install pytest
        python setup.py build_lib
        pip install -e .
        pytest
